let generalKnowledgeQuestions = [
  [
    "What is the capital of Australia?",
    "Sydney",
    "Melbourne",
    "Canberra",
    "Perth",
    2,
  ],
  [
    "Who painted the famous artwork 'The Starry Night'?",
    "Pablo Picasso",
    "Vincent van Gogh",
    "Leonardo da Vinci",
    "Claude Monet",
    1,
  ],
  ["What is the currency of Japan?", "Yen", "Won", "Dollar", "Euro", 0],
  [
    "In which year did the Berlin Wall fall?",
    "1989",
    "1991",
    "1987",
    "1993",
    0,
  ],
  [
    "Which philosopher wrote the book 'Thus Spoke Zarathustra'?",
    "Friedrich Nietzsche",
    "Socrates",
    "Plato",
    "Aristotle",
    0,
  ],
  [
    "What is the chemical formula for caffeine?",
    "C8H10N4O2",
    "H2O",
    "NaCl",
    "CO2",
    0,
  ],
  [
    "What is the largest planet in our solar system?",
    "Mars",
    "Jupiter",
    "Venus",
    "Saturn",
    1,
  ],
  [
    "What is the symbol for the chemical element 'Oxygen'?",
    "O",
    "C",
    "H",
    "N",
    0,
  ],
  [
    "Who developed the theory of general relativity?",
    "Isaac Newton",
    "Stephen Hawking",
    "Albert Einstein",
    "Galileo Galilei",
    2,
  ],
  [
    "What is the process of converting a solid directly into a gas called?",
    "Melting",
    "Freezing",
    "Condensation",
    "Sublimation",
    3,
  ],
  [
    "What is the smallest unit of matter?",
    "Atom",
    "Molecule",
    "Cell",
    "Electron",
    0,
  ],
  [
    "What is the study of fossils called?",
    "Paleontology",
    "Geology",
    "Biology",
    "Anthropology",
    0,
  ],
  ["What is the capital of France?", "Paris", "London", "Berlin", "Madrid", 0],
  [
    "Who wrote the novel 'To Kill a Mockingbird'?",
    "Harper Lee",
    "J.D. Salinger",
    "Mark Twain",
    "Charles Dickens",
    0,
  ],
  ["How many sides does a hexagon have?", "4", "6", "8", "10", 1],
  [
    "What is the capital of China?",
    "Beijing",
    "Shanghai",
    "Hong Kong",
    "Tokyo",
    0,
  ],
  [
    "Who is the author of the famous novel '1984'?",
    "George Orwell",
    "F. Scott Fitzgerald",
    "Herman Melville",
    "J.R.R. Tolkien",
    0,
  ],
  [
    "Which country is known as the 'Land of the Midnight Sun'?",
    "Norway",
    "Sweden",
    "Finland",
    "Iceland",
    0,
  ],
  [
    "What is the largest desert in the world?",
    "Sahara Desert",
    "Gobi Desert",
    "Arabian Desert",
    "Kalahari Desert",
    0,
  ],
  [
    "Who discovered penicillin?",
    "Alexander Fleming",
    "Louis Pasteur",
    "Marie Curie",
    "Thomas Edison",
    0,
  ],
  [
    "What is the national animal of Canada?",
    "Lion",
    "Bald Eagle",
    "Panda",
    "Beaver",
    3,
  ],
  [
    "Which planet is known as the 'Blue Planet'?",
    "Mars",
    "Venus",
    "Earth",
    "Neptune",
    2,
  ],
  ["What is the chemical symbol for silver?", "Au", "Ag", "Fe", "Pb", 1],
  [
    "Who invented the light bulb?",
    "Thomas Edison",
    "Benjamin Franklin",
    "Nikola Tesla",
    "Isaac Newton",
    0,
  ],
  [
    "What is the largest waterfall in the world?",
    "Angel Falls",
    "Victoria Falls",
    "Niagara Falls",
    "Iguazu Falls",
    1,
  ],
  [
    "What is the capital of Brazil?",
    "Rio de Janeiro",
    "Sao Paulo",
    "Brasilia",
    "Buenos Aires",
    2,
  ],
  [
    "Which city serves as the capital of South Africa?",
    "Johannesburg",
    "Cape Town",
    "Pretoria",
    "Nairobi",
    2,
  ],
  [
    "What is the capital of Thailand?",
    "Bangkok",
    "Phuket",
    "Chiang Mai",
    "Ho Chi Minh City",
    0,
  ],
  [
    "Which city is the capital of Canada?",
    "Toronto",
    "Montreal",
    "Vancouver",
    "Ottawa",
    3,
  ],
  [
    "What is the capital of Saudi Arabia?",
    "Dubai",
    "Riyadh",
    "Mecca",
    "Doha",
    1,
  ],
  [
    "Which city serves as the capital of Argentina?",
    "Buenos Aires",
    "Santiago",
    "Lima",
    "Bogota",
    0,
  ],
  [
    "What is the capital of Sweden?",
    "Stockholm",
    "Copenhagen",
    "Oslo",
    "Helsinki",
    0,
  ],
  [
    "Which city is the capital of Turkey?",
    "Istanbul",
    "Ankara",
    "Athens",
    "Rome",
    1,
  ],
  [
    "What is the capital of South Korea?",
    "Tokyo",
    "Beijing",
    "Seoul",
    "Pyongyang",
    2,
  ],
  [
    "Which city serves as the capital of Australia?",
    "Sydney",
    "Melbourne",
    "Canberra",
    "Perth",
    2,
  ],
];

let historyQuestions = [
  ["Which year did World War I begin?", "1914", "1915", "1916", "1917", 0],
  [
    "Who was the first President of the United States?",
    "George Washington",
    "Thomas Jefferson",
    "Abraham Lincoln",
    "John Adams",
    0,
  ],
  [
    "Which city was the capital of the Aztec empire?",
    "Tenochtitlan",
    "Cusco",
    "Machu Picchu",
    "Teotihuacan",
    0,
  ],
  [
    "Who painted the ceiling of the Sistine Chapel?",
    "Michelangelo",
    "Leonardo da Vinci",
    "Raphael",
    "Donatello",
    0,
  ],
  [
    "In which year did the Industrial Revolution begin?",
    "1750",
    "1800",
    "1850",
    "1900",
    0,
  ],
  [
    "Who wrote the play 'Romeo and Juliet'?",
    "William Shakespeare",
    "Christopher Marlowe",
    "George Bernard Shaw",
    "Oscar Wilde",
    0,
  ],
  [
    "Which country was the first to circumnavigate the globe?",
    "Portugal",
    "Spain",
    "England",
    "France",
    1,
  ],
  [
    "Who was the last pharaoh of ancient Egypt?",
    "Cleopatra",
    "Nefertiti",
    "Hatshepsut",
    "Tutankhamun",
    0,
  ],
  [
    "In which year did the American Civil War end?",
    "1865",
    "1870",
    "1863",
    "1867",
    0,
  ],
  [
    "Which European explorer reached India by sea in 1498?",
    "Christopher Columbus",
    "Vasco da Gama",
    "Ferdinand Magellan",
    "James Cook",
    1,
  ],
  [
    "Who was the first female Prime Minister of the United Kingdom?",
    "Margaret Thatcher",
    "Angela Merkel",
    "Theresa May",
    "Indira Gandhi",
    0,
  ],
  [
    "In which year did the French Revolution begin?",
    "1789",
    "1800",
    "1750",
    "1820",
    0,
  ],
  [
    "Who is credited with the invention of the printing press?",
    "Johannes Gutenberg",
    "Leonardo da Vinci",
    "Isaac Newton",
    "Galileo Galilei",
    0,
  ],
  [
    "Which city was the capital of the Roman Empire?",
    "Rome",
    "Athens",
    "Alexandria",
    "Constantinople",
    3,
  ],
  [
    "Who delivered the famous 'I Have a Dream' speech?",
    "Martin Luther King Jr.",
    "Nelson Mandela",
    "Barack Obama",
    "Malcolm X",
    0,
  ],
  ["Which year did World War I begin?", "1914", "1915", "1916", "1917", 0],
  [
    "Who was the first President of the United States?",
    "George Washington",
    "Thomas Jefferson",
    "Abraham Lincoln",
    "John F. Kennedy",
    0,
  ],
  [
    "Which country was ruled by Adolf Hitler during World War II?",
    "France",
    "Germany",
    "Russia",
    "Italy",
    1,
  ],
  ["When did the American Civil War end?", "1863", "1864", "1865", "1866", 2],
  [
    "Who was the leader of the Soviet Union during World War II?",
    "Joseph Stalin",
    "Vladimir Lenin",
    "Mikhail Gorbachev",
    "Nikita Khrushchev",
    0,
  ],
  [
    "Which city was the capital of the Byzantine Empire?",
    "Athens",
    "Rome",
    "Constantinople",
    "Alexandria",
    2,
  ],
  [
    "When did the Industrial Revolution take place?",
    "16th century",
    "17th century",
    "18th century",
    "19th century",
    2,
  ],
  [
    "Who wrote the book 'The Communist Manifesto'?",
    "Karl Marx",
    "Adam Smith",
    "John Locke",
    "Thomas Hobbes",
    0,
  ],
  [
    "Which country colonized India?",
    "France",
    "Spain",
    "Portugal",
    "United Kingdom",
    3,
  ],
  [
    "Who was the last Queen of France before the French Revolution?",
    "Catherine the Great",
    "Marie Antoinette",
    "Queen Victoria",
    "Elizabeth I",
    1,
  ],
  [
    "When did the Renaissance period occur?",
    "14th century",
    "15th century",
    "16th century",
    "17th century",
    2,
  ],
  [
    "Which war was fought between North and South Korea from 1950 to 1953?",
    "World War I",
    "Vietnam War",
    "Korean War",
    "Cold War",
    2,
  ],
  [
    "Who discovered America?",
    "Christopher Columbus",
    "Amerigo Vespucci",
    "Vasco da Gama",
    "Ferdinand Magellan",
    0,
  ],
  [
    "Which civilization built the Great Wall of China?",
    "Mayans",
    "Aztecs",
    "Incas",
    "Chinese",
    3,
  ],
  [
    "Who was the first Emperor of Rome?",
    "Julius Caesar",
    "Augustus",
    "Nero",
    "Constantine",
    1,
  ],
  ["When did the French Revolution begin?", "1787", "1788", "1789", "1790", 2],
  [
    "Which country was Nelson Mandela the President of?",
    "South Africa",
    "Kenya",
    "Nigeria",
    "Egypt",
    0,
  ],
  ["When was the Magna Carta signed?", "1210", "1215", "1220", "1225", 1],
  [
    "Who was the first female Prime Minister of the United Kingdom?",
    "Margaret Thatcher",
    "Angela Merkel",
    "Theresa May",
    "Jacinda Ardern",
    0,
  ],
  [
    "Which country was Napoleon Bonaparte born in?",
    "France",
    "Italy",
    "Germany",
    "Spain",
    1,
  ],
  [
    "When was the Declaration of Independence signed?",
    "1774",
    "1775",
    "1776",
    "1777",
    2,
  ],
  [
    "Who led the Bolshevik Revolution in Russia in 1917?",
    "Vladimir Lenin",
    "Leon Trotsky",
    "Joseph Stalin",
    "Mikhail Gorbachev",
    0,
  ],
  [
    "Which ancient civilization built the city of Machu Picchu?",
    "Mayans",
    "Aztecs",
    "Incas",
    "Romans",
    2,
  ],
  ["When was the Berlin Wall demolished?", "1985", "1987", "1989", "1991", 2],
  [
    "Who was the first President of the Russian Federation?",
    "Vladimir Putin",
    "Boris Yeltsin",
    "Mikhail Gorbachev",
    "Dmitry Medvedev",
    1,
  ],
  [
    "Which ancient civilization built the pyramids of Egypt?",
    "Greeks",
    "Persians",
    "Egyptians",
    "Babylonians",
    2,
  ],
  [
    "When was the Battle of Waterloo fought?",
    "1804",
    "1810",
    "1815",
    "1820",
    2,
  ],
  [
    "Who was the first President of the United States of America?",
    "John Adams",
    "Thomas Jefferson",
    "George Washington",
    "James Madison",
    2,
  ],
  [
    "Which country was once ruled by the great warrior Genghis Khan?",
    "Mongolia",
    "China",
    "India",
    "Russia",
    0,
  ],
  [
    "When did the Russian Revolution take place?",
    "1905",
    "1910",
    "1917",
    "1922",
    2,
  ],
  [
    "Who was the first African-American President of the United States?",
    "Barack Obama",
    "Joe Biden",
    "Bill Clinton",
    "George W. Bush",
    0,
  ],
  [
    "Who led the Salt March (Dandi March) in India as part of the Civil Disobedience Movement?",
    "Jawaharlal Nehru",
    "Mahatma Gandhi",
    "Subhash Chandra Bose",
    "Bhagat Singh",
    1,
  ],
  [
    "In which year did India gain independence from British rule?",
    "1945",
    "1947",
    "1950",
    "1962",
    1,
  ],
  [
    "Who is known as the 'Father of the Indian Constitution'?",
    "Mahatma Gandhi",
    "Jawaharlal Nehru",
    "B.R. Ambedkar",
    "Sardar Vallabhbhai Patel",
    2,
  ],
  [
    "Which event marked the formal beginning of the Indian National Movement?",
    "Revolt of 1857",
    "Partition of Bengal in 1905",
    "Formation of Indian National Congress in 1885",
    "Quit India Movement in 1942",
    2,
  ],
  [
    "Who was the first Prime Minister of India?",
    "Jawaharlal Nehru",
    "Indira Gandhi",
    "Rajiv Gandhi",
    "Morarji Desai",
    0,
  ],
  [
    "Who was the last Viceroy of India?",
    "Lord Mountbatten",
    "Lord Curzon",
    "Lord Dalhousie",
    "Lord Canning",
    0,
  ],
  [
    "Which Indian king is known as the 'Lion of Punjab'?",
    "Raja Raja Chola",
    "Shivaji",
    "Akbar",
    "Maharaja Ranjit Singh",
    3,
  ],
  [
    "Who was the leader of the Indian National Army (Azad Hind Fauj) during World War II?",
    "Subhash Chandra Bose",
    "Jawaharlal Nehru",
    "Sardar Vallabhbhai Patel",
    "Bhagat Singh",
    0,
  ],
  [
    "Who was the first Indian woman to become the President of the Indian National Congress?",
    "Indira Gandhi",
    "Sarojini Naidu",
    "Vijaya Lakshmi Pandit",
    "Annie Besant",
    1,
  ],
  [
    "Who is known as the 'Iron Man of India'?",
    "Jawaharlal Nehru",
    "Sardar Vallabhbhai Patel",
    "Subhash Chandra Bose",
    "Lal Bahadur Shastri",
    1,
  ],
  [
    "Which Indian state was the first to achieve full statehood?",
    "Maharashtra",
    "Kerala",
    "Tamil Nadu",
    "Andhra Pradesh",
    3,
  ],
  [
    "Who composed the music for the Indian National Anthem?",
    "Rabindranath Tagore",
    "Bhimsen Joshi",
    "A.R. Rahman",
    "M.S. Subbulakshmi",
    0,
  ],
  [
    "Which Indian city served as the capital of British India from 1911 to 1947?",
    "Kolkata",
    "Mumbai",
    "Chennai",
    "Delhi",
    3,
  ],
  [
    "Who was the first Indian to win the Nobel Prize?",
    "Rabindranath Tagore",
    "C.V. Raman",
    "Hargobind Khorana",
    "Amartya Sen",
    0,
  ],
  [
    "Who is known as the 'Nightingle of India'?",
    "Lata Mangeshkar",
    "Asha Bhosle",
    "Sarojini Naidu",
    "M.S. Subbulakshmi",
    2,
  ],
];

let geographyQuestions = [
  [
    "Which country is known as the 'Land of the Rising Sun'?",
    "China",
    "Japan",
    "South Korea",
    "Thailand",
    1,
  ],
  [
    "Which river is the longest in the world?",
    "Nile",
    "Amazon",
    "Mississippi",
    "Yangtze",
    0,
  ],
  [
    "Which mountain range is the longest in the world?",
    "Andes",
    "Rocky Mountains",
    "Himalayas",
    "Alps",
    0,
  ],
  [
    "Which ocean is the largest?",
    "Pacific Ocean",
    "Atlantic Ocean",
    "Indian Ocean",
    "Arctic Ocean",
    0,
  ],
  [
    "Which country is known as the 'Land of Fire and Ice'?",
    "Norway",
    "Iceland",
    "Greenland",
    "Sweden",
    1,
  ],
  [
    "What is the tallest mountain in the world?",
    "Mount Everest",
    "K2",
    "Kangchenjunga",
    "Makalu",
    0,
  ],
  [
    "Which country is home to the Great Barrier Reef?",
    "Australia",
    "Indonesia",
    "Maldives",
    "Philippines",
    0,
  ],
  [
    "What is the largest island in the world?",
    "Greenland",
    "Madagascar",
    "Borneo",
    "New Guinea",
    0,
  ],
  [
    "Which continent is the driest in the world?",
    "Africa",
    "Australia",
    "Asia",
    "South America",
    1,
  ],
  [
    "Which country is known as the 'Land of a Thousand Lakes'?",
    "Finland",
    "Canada",
    "Sweden",
    "Norway",
    0,
  ],
  [
    "Which country is known as the 'Land of Smiles'?",
    "Thailand",
    "Brazil",
    "Italy",
    "India",
    0,
  ],
  [
    "What is the largest lake in Africa?",
    "Lake Victoria",
    "Lake Tanganyika",
    "Lake Malawi",
    "Lake Turkana",
    0,
  ],
  [
    "Which continent is the largest by land area?",
    "Asia",
    "Africa",
    "North America",
    "South America",
    0,
  ],
  [
    "Which country is known as the 'Land of the Rising Sun'?",
    "China",
    "Japan",
    "South Korea",
    "Vietnam",
    1,
  ],
  [
    "Which is the longest river in the world?",
    "Nile River",
    "Amazon River",
    "Yangtze River",
    "Mississippi River",
    0,
  ],
  [
    "Which country is known as the 'Land Down Under'?",
    "Australia",
    "New Zealand",
    "Canada",
    "South Africa",
    0,
  ],
  [
    "Which city is located at the confluence of the Danube and Sava rivers?",
    "Budapest",
    "Vienna",
    "Prague",
    "Belgrade",
    3,
  ],
  [
    "What is the largest country in South America?",
    "Brazil",
    "Argentina",
    "Colombia",
    "Peru",
    0,
  ],
  [
    "Which strait separates Asia and North America?",
    "Strait of Gibraltar",
    "Strait of Hormuz",
    "Strait of Malacca",
    "Bering Strait",
    3,
  ],
  [
    "Which country is known for its fjords?",
    "Norway",
    "Sweden",
    "Finland",
    "Denmark",
    0,
  ],
  [
    "Which city is located on the banks of the Nile River?",
    "Cairo",
    "Rome",
    "Athens",
    "Paris",
    0,
  ],
  [
    "Which country is the largest producer of coffee?",
    "Brazil",
    "Colombia",
    "Vietnam",
    "Ethiopia",
    0,
  ],
  [
    "Which country is the smallest in terms of land area?",
    "Monaco",
    "Maldives",
    "San Marino",
    "Nauru",
    2,
  ],
  [
    "What is the largest coral reef system in the world?",
    "Great Barrier Reef",
    "Mesoamerican Barrier Reef",
    "Andros Barrier Reef",
    "Red Sea Coral Reef",
    0,
  ],
  [
    "Which country is known as the 'Land of Fire and Ice'?",
    "Greenland",
    "Iceland",
    "Finland",
    "Sweden",
    1,
  ],
  [
    "Which city is located at the mouth of the Amazon River?",
    "Lima",
    "Buenos Aires",
    "Rio de Janeiro",
    "Belem",
    3,
  ],
  [
    "What is the capital of India?",
    "New Delhi",
    "Mumbai",
    "Kolkata",
    "Chennai",
    0,
  ],
  [
    "Which is the highest mountain peak in India?",
    "Kangchenjunga",
    "Mount Everest",
    "Nanda Devi",
    "Kamet",
    0,
  ],
  [
    "Which is the longest river in India?",
    "Ganges",
    "Yamuna",
    "Brahmaputra",
    "Godavari",
    0,
  ],
  [
    "Which is the largest state in India by area?",
    "Rajasthan",
    "Madhya Pradesh",
    "Maharashtra",
    "Uttar Pradesh",
    0,
  ],
  [
    "Which is the southernmost point of the Indian mainland?",
    "Cape Comorin",
    "Rameswaram",
    "Kanyakumari",
    "Trivandrum",
    2,
  ],
  [
    "Which city is known as the 'Pink City' of India?",
    "Jaipur",
    "Jaisalmer",
    "Udaipur",
    "Agra",
    0,
  ],
  [
    "Which is the largest freshwater lake in India?",
    "Dal Lake",
    "Vembanad Lake",
    "Wular Lake",
    "Chilika Lake",
    2,
  ],
  [
    "Which state in India is known as the 'Land of Five Rivers'?",
    "Punjab",
    "Haryana",
    "Uttar Pradesh",
    "Gujarat",
    0,
  ],
  [
    "Which is the wettest place in India?",
    "Mawsynram",
    "Cherrapunji",
    "Agumbe",
    "Dibrugarh",
    0,
  ],
  [
    "Which is the largest city in India by population?",
    "Mumbai",
    "Delhi",
    "Kolkata",
    "Chennai",
    0,
  ],
  [
    "Which is the largest saltwater lake in India?",
    "Chilika Lake",
    "Dal Lake",
    "Sambhar Lake",
    "Vembanad Lake",
    2,
  ],
  [
    "Which state in India is known as the 'Land of the Gods'?",
    "Uttarakhand",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Sikkim",
    0,
  ],
  [
    "Which is the largest tiger reserve in India?",
    "Kaziranga National Park",
    "Sunderbans National Park",
    "Bandhavgarh National Park",
    "Jim Corbett National Park",
    3,
  ],
  [
    "Which is the largest delta in India?",
    "Ganga-Brahmaputra Delta",
    "Krishna Delta",
    "Godavari Delta",
    "Kaveri Delta",
    0,
  ],
  [
    "Which state in India is known as the 'Spice Garden of India'?",
    "Kerala",
    "Karnataka",
    "Tamil Nadu",
    "Andhra Pradesh",
    0,
  ],
  [
    "Which city is known as the 'Manchester of South India'?",
    "Coimbatore",
    "Kochi",
    "Mysore",
    "Hyderabad",
    0,
  ],
  [
    "Which is the largest cave temple in India?",
    "Kailasa Temple",
    "Ellora Caves",
    "Ajanta Caves",
    "Amarnath Cave",
    1,
  ],
  [
    "Which state in India is known as the 'Land of Festivals'?",
    "Rajasthan",
    "Gujarat",
    "Maharashtra",
    "West Bengal",
    3,
  ],
  [
    "Which is the driest place in India?",
    "Jaisalmer",
    "Leh",
    "Bikaner",
    "Kutch",
    1,
  ],
  [
    "Which state in India is known as the 'Land of Backwaters'?",
    "Kerala",
    "Tamil Nadu",
    "Karnataka",
    "Andhra Pradesh",
    0,
  ],
  [
    "Which is the largest mangrove forest in India?",
    "Sundarbans",
    "Bhitarkanika",
    "Pichavaram",
    "Mangrove National Park",
    0,
  ],
  [
    "Which city is located on the banks of the Brahmaputra River?",
    "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Tezpur",
    0,
  ],
  [
    "Which state in India is known as the 'Land of Lakes'?",
    "Madhya Pradesh",
    "Rajasthan",
    "Gujarat",
    "Maharashtra",
    1,
  ],
  [
    "Which is the largest coral reef system in India?",
    "Gulf of Mannar",
    "Lakshadweep Coral Reef",
    "Andaman and Nicobar Coral Reef",
    "Netrani Island",
    2,
  ],
  [
    "Which city is known as the 'City of Lakes'?",
    "Udaipur",
    "Jaipur",
    "Jaisalmer",
    "Pushkar",
    0,
  ],
  [
    "Which is the highest waterfall in India?",
    "Dudhsagar Falls",
    "Jog Falls",
    "Barkana Falls",
    "Kunchikal Falls",
    1,
  ],
  [
    "Which state in India is known as the 'Land of Forests'?",
    "Assam",
    "Madhya Pradesh",
    "Uttarakhand",
    "Arunachal Pradesh",
    3,
  ],
  [
    "Which is the only floating national park in India?",
    "Kaziranga National Park",
    "Hemis National Park",
    "Keibul Lamjao National Park",
    "Ranthambore National Park",
    2,
  ],
  [
    "Which state in India is known as the 'Land of Rivers'?",
    "Uttar Pradesh",
    "Bihar",
    "West Bengal",
    "Maharashtra",
    1,
  ],
];

let mathLogicQuestions = [
  ["What is the square root of 64?", "4", "8", "6", "10", 1],
  ["Simplify the expression: 3 * (4 + 2) - 8 / 2", "16", "20", "18", "14", 2],
  [
    "What is the value of pi (π) to two decimal places?",
    "3.12",
    "3.14",
    "3.16",
    "3.10",
    1,
  ],
  ["Solve the equation for x: 2x + 5 = 17", "6", "8", "7", "9", 2],
  [
    "What is the next number in the sequence: 1, 4, 9, 16, __",
    "25",
    "26",
    "27",
    "32",
    0,
  ],
  [
    "If a triangle has angles measuring 30 degrees, 60 degrees, and 90 degrees, what type of triangle is it?",
    "Equilateral triangle",
    "Isosceles triangle",
    "Scalene triangle",
    "Right triangle",
    3,
  ],
  ["What is the value of 5! (factorial)?", "120", "60", "240", "720", 3],
  ["Solve for x: 2x - 5 = 3x + 4", "-9", "9", "6", "14", 0],
  [
    "If a = 4 and b = 7, what is the value of a^2 + b^2?",
    "41",
    "65",
    "57",
    "45",
    2,
  ],
  [
    "What is the sum of the interior angles of a triangle?",
    "90 degrees",
    "180 degrees",
    "270 degrees",
    "360 degrees",
    1,
  ],
  ["How many sides does a heptagon have?", "5", "6", "7", "8", 2],
  [
    "Simplify the expression: 3x + 2y - 5x + 4y",
    "-2x + 6y",
    "-2x - 2y",
    "2x + 6y",
    "2x - 2y",
    1,
  ],
  [
    "If a train travels at a speed of 60 miles per hour, how far will it travel in 3 hours?",
    "90 miles",
    "120 miles",
    "150 miles",
    "180 miles",
    3,
  ],
  ["What is the value of log base 10 of 100?", "1", "10", "100", "2", 2],
  ["If 2x + 3 = 9, what is the value of x?", "2", "3", "4", "5", 1],

  // Math Questions (20)
  ["What is the value of e ?", "3.142", "2.653", "2.718", "2.879", 2],
  ["Solve the equation: 2x + 5 = 15", "x = 5", "x = 6", "x = 7", "x = 8", 1],
  ["What is the square root of 256?", "14", "16", "18", "12", 1],
  ["What is 12 multiplied by 9?", "92", "108", "106", "118", 1],
  ["Simplify: 4(2 + 5) - 3(1 + 2)", "25", "14", "12", "9", 3],
  [
    "What is the next number in the sequence: 1, 1, 2, 3, 5, 8, ...",
    "13",
    "14",
    "15",
    "16",
    0,
  ],
  [
    "What is the value of 7! (7 factorial)?",
    "5040",
    "40320",
    "362880",
    "518400",
    1,
  ],
  ["Solve the equation: 3x - 7 = 20", "x = 7", "x = 9", "x = 10", "x = 11", 2],
  [
    "What is the sum of angles in a kite?",
    "90 degrees",
    "180 degrees",
    "270 degrees",
    "360 degrees",
    3,
  ],
  [
    "If a circle has a diameter of 10, what is its radius?",
    "5",
    "10",
    "15",
    "20",
    0,
  ],
  [
    "John's father is twice as old as John. If John is 10 years old, how old is his father?",
    "10 years old",
    "20 years old",
    "30 years old",
    "40 years old",
    1,
  ],
  [
    "If a plane crashes on the border between the US and Canada, where would the survivors be buried?",
    "US",
    "Canada",
    "Neither",
    "Both",
    3,
  ],
  [
    "A farmer has 17 cows. All but 9 die. How many cows are left?",
    "9",
    "8",
    "7",
    "None",
    0,
  ],
  ["How many months have 28 days?", "1", "6", "12", "All", 3],
  [
    "How many legs does a dog have if you call its tail a leg?",
    "3",
    "4",
    "5",
    "None",
    1,
  ],
  [
    "Mary's father has 5 daughters: Nana, Nene, Nini, Nono, and ???",
    "Mama",
    "Mary",
    "Moni",
    "Meme",
    1,
  ],
  [
    "If there are 12 fish and half of them drown, how many are left?",
    "6",
    "3",
    "0",
    "12",
    3,
  ],
  [
    "If you had only one match and entered a dark room containing an oil lamp, some kindling wood, and a newspaper, which would you light first?",
    "Match",
    "Oil lamp",
    "Kindling wood",
    "Newspaper",
    0,
  ],
  [
    "A plane crashes on the border of the US and Canada. Where would the survivors be buried?",
    "US",
    "Canada",
    "Neither",
    "Both",
    2,
  ],
  ["How many sides does a circle have?", "0", "1", "2", "Infinite", 1],
];

let scienceTechQuestions = [
  ["What is the chemical symbol for gold?", "Au", "Ag", "Pt", "Go", 0],
  [
    "What is the SI unit of electric current?",
    "Volt",
    "Ampere",
    "Ohm",
    "Watt",
    1,
  ],
  [
    "What is the process by which plants convert sunlight into energy called?",
    "Photosynthesis",
    "Respiration",
    "Fermentation",
    "Transpiration",
    0,
  ],
  [
    "Which particle has a positive charge?",
    "Proton",
    "Neutron",
    "Electron",
    "Photon",
    0,
  ],
  [
    "Who is known as the 'Father of Computer Science'?",
    "Alan Turing",
    "Bill Gates",
    "Steve Jobs",
    "Charles Babbage",
    3,
  ],
  [
    "What is the largest planet in our solar system?",
    "Mercury",
    "Venus",
    "Jupiter",
    "Mars",
    2,
  ],
  [
    "What is the unit of measurement for force?",
    "Newton",
    "Watt",
    "Joule",
    "Pascal",
    0,
  ],
  [
    "What is the process of a solid changing directly into a gas called?",
    "Sublimation",
    "Evaporation",
    "Condensation",
    "Fusion",
    0,
  ],
  [
    "What is the branch of science that studies the Earth's atmosphere?",
    "Biology",
    "Chemistry",
    "Geology",
    "Meteorology",
    3,
  ],
  [
    "What is the unit of measurement for frequency?",
    "Hertz",
    "Watt",
    "Ampere",
    "Ohm",
    0,
  ],
  [
    "Which scientist developed the theory of general relativity?",
    "Isaac Newton",
    "Marie Curie",
    "Albert Einstein",
    "Galileo Galilei",
    2,
  ],
  [
    "What is the SI unit of temperature?",
    "Kelvin",
    "Celsius",
    "Fahrenheit",
    "Rankine",
    0,
  ],
  [
    "What is the process of breaking down complex substances into simpler ones called?",
    "Oxidation",
    "Hydration",
    "Combustion",
    "Decomposition",
    3,
  ],
  [
    "What is the study of heredity and variation in organisms called?",
    "Genetics",
    "Ecology",
    "Botany",
    "Zoology",
    0,
  ],
  [
    "What is the unit of measurement for electrical resistance?",
    "Volt",
    "Ampere",
    "Ohm",
    "Watt",
    2,
  ],
  [
    "Which gas makes up the majority of the Earth's atmosphere?",
    "Nitrogen",
    "Oxygen",
    "Carbon dioxide",
    "Argon",
    0,
  ],
  [
    "Who is credited with discovering the structure of DNA?",
    "Francis Crick",
    "Rosalind Franklin",
    "James Watson",
    "Gregor Mendel",
    1,
  ],
  [
    "What is the process of converting a liquid into a solid called?",
    "Evaporation",
    "Condensation",
    "Freezing",
    "Sublimation",
    2,
  ],
  [
    "What is the unit of measurement for energy?",
    "Joule",
    "Watt",
    "Ampere",
    "Volt",
    0,
  ],
  [
    "Which element has the atomic number 6?",
    "Oxygen",
    "Carbon",
    "Hydrogen",
    "Nitrogen",
    1,
  ],
  ["What is the SI unit of pressure?", "Pascal", "Newton", "Joule", "Watt", 0],
  [
    "What is the process of converting a gas into a liquid called?",
    "Evaporation",
    "Condensation",
    "Sublimation",
    "Vaporization",
    1,
  ],
  [
    "What is the study of the Earth's physical structure, history, and the processes that shape it called?",
    "Biology",
    "Chemistry",
    "Geology",
    "Physics",
    2,
  ],
  [
    "Which planet is known as the 'Blue Planet'?",
    "Mars",
    "Jupiter",
    "Earth",
    "Neptune",
    2,
  ],
  [
    "What is the unit of measurement for electric potential difference?",
    "Volt",
    "Ampere",
    "Ohm",
    "Watt",
    0,
  ],
  [
    "What is the process of combining hydrogen atoms to form helium called?",
    "Fusion",
    "Fission",
    "Combustion",
    "Ionization",
    0,
  ],
  [
    "Which branch of science deals with the study of sound and its properties?",
    "Biology",
    "Chemistry",
    "Geology",
    "Acoustics",
    3,
  ],
  [
    "What is the chemical formula for table salt?",
    "NaCl",
    "H2O",
    "CO2",
    "CH4",
    0,
  ],
  [
    "Who is credited with inventing the telephone?",
    "Thomas Edison",
    "Nikola Tesla",
    "Alexander Graham Bell",
    "Benjamin Franklin",
    2,
  ],
  [
    "What is the branch of biology that deals with the study of plants?",
    "Botany",
    "Zoology",
    "Genetics",
    "Ecology",
    0,
  ],
  [
    "What is the unit of measurement for electric power?",
    "Joule",
    "Watt",
    "Ampere",
    "Volt",
    1,
  ],
  [
    "Which gas is responsible for the ozone layer depletion?",
    "Carbon dioxide",
    "Nitrogen",
    "Oxygen",
    "Chlorofluorocarbons (CFCs)",
    3,
  ],
  [
    "What is the process of converting light energy into electrical energy called?",
    "Reflection",
    "Refraction",
    "Photosynthesis",
    "Solar energy conversion",
    3,
  ],
  [
    "Which scientist is known for the laws of motion?",
    "Isaac Newton",
    "Marie Curie",
    "Albert Einstein",
    "Galileo Galilei",
    0,
  ],
  [
    "What is the study of the behavior and interaction of matter and energy called?",
    "Physics",
    "Chemistry",
    "Biology",
    "Geology",
    0,
  ],
  [
    "What is the largest moon in our solar system?",
    "Europa",
    "Titan",
    "Ganymede",
    "Callisto",
    2,
  ],
  [
    "What is the unit of measurement for electric resistance?",
    "Ohm",
    "Ampere",
    "Watt",
    "Volt",
    0,
  ],
  [
    "Which scientist proposed the theory of general relativity?",
    "Isaac Newton",
    "Marie Curie",
    "Albert Einstein",
    "Galileo Galilei",
    2,
  ],
  [
    "What is the process of converting electrical energy into mechanical energy called?",
    "Transformation",
    "Transduction",
    "Transcription",
    "Electromechanical conversion",
    3,
  ],
  [
    "Which element is essential for all organic compounds?",
    "Oxygen",
    "Carbon",
    "Hydrogen",
    "Nitrogen",
    1,
  ],
];

let sportsQuestions = [
  [
    "Who won the FIFA World Cup in 2018?",
    "Brazil",
    "Germany",
    "France",
    "Spain",
    2,
  ],
  [
    "Which country has won the most Olympic gold medals?",
    "United States",
    "China",
    "Russia",
    "Germany",
    0,
  ],
  [
    "Who holds the record for the most home runs in Major League Baseball?",
    "Babe Ruth",
    "Barry Bonds",
    "Hank Aaron",
    "Alex Rodriguez",
    1,
  ],
  [
    "Which tennis player has won the most Grand Slam titles in history?",
    "Roger Federer",
    "Rafael Nadal",
    "Novak Djokovic",
    "Serena Williams",
    0,
  ],
  [
    "Which team has won the most Super Bowl championships?",
    "Pittsburgh Steelers",
    "New England Patriots",
    "Dallas Cowboys",
    "San Francisco 49ers",
    1,
  ],
  [
    "Who is the all-time leading scorer in NBA history?",
    "Michael Jordan",
    "LeBron James",
    "Kobe Bryant",
    "Kareem Abdul-Jabbar",
    3,
  ],
  [
    "Which country has won the most FIFA World Cup titles?",
    "Brazil",
    "Germany",
    "Italy",
    "Argentina",
    0,
  ],
  [
    "Who is the fastest man in the world?",
    "Usain Bolt",
    "Tyson Gay",
    "Yohan Blake",
    "Justin Gatlin",
    0,
  ],
  [
    "Which golfer has the most major championships in golf history?",
    "Tiger Woods",
    "Jack Nicklaus",
    "Arnold Palmer",
    "Phil Mickelson",
    1,
  ],
  [
    "Which team has won the most NBA championships?",
    "Boston Celtics",
    "Los Angeles Lakers",
    "Chicago Bulls",
    "Golden State Warriors",
    1,
  ],
  [
    "Who holds the record for the most goals scored in a single NHL season?",
    "Mario Lemieux",
    "Wayne Gretzky",
    "Bobby Orr",
    "Jaromir Jagr",
    1,
  ],
  [
    "Which country has won the most medals in the history of the Summer Olympics?",
    "United States",
    "China",
    "Soviet Union",
    "Great Britain",
    0,
  ],
  [
    "Who won the UEFA Champions League in 2020?",
    "Bayern Munich",
    "Paris Saint-Germain",
    "Real Madrid",
    "Liverpool",
    0,
  ],
  [
    "Which boxer has the highest knockout percentage in heavyweight history?",
    "Muhammad Ali",
    "Mike Tyson",
    "George Foreman",
    "Lennox Lewis",
    1,
  ],
  [
    "Who is the most decorated Olympian of all time?",
    "Michael Phelps",
    "Usain Bolt",
    "Carl Lewis",
    "Simone Biles",
    0,
  ],
  [
    "Who is the highest run-scorer in the history of Test cricket?",
    "Sachin Tendulkar",
    "Ricky Ponting",
    "Jacques Kallis",
    "Kumar Sangakkara",
    0,
  ],
  [
    "Who is the leading wicket-taker in the history of Test cricket?",
    "Muttiah Muralitharan",
    "Shane Warne",
    "Anil Kumble",
    "James Anderson",
    3,
  ],
  [
    "Which team won the ICC Cricket World Cup in 2019?",
    "India",
    "England",
    "Australia",
    "New Zealand",
    1,
  ],
  [
    "Who is the current captain of the Indian cricket team?",
    "Virat Kohli",
    "Rohit Sharma",
    "KL Rahul",
    "Shikhar Dhawan",
    0,
  ],
  // Cricket Questions (20)
  [
    "Who is known as the 'God of Cricket'?",
    "Sachin Tendulkar",
    "Virat Kohli",
    "Ricky Ponting",
    "Brian Lara",
    0,
  ],
  [
    "Which country has won the most Cricket World Cups?",
    "Australia",
    "India",
    "England",
    "West Indies",
    0,
  ],
  [
    "Who is the leading run-scorer in international cricket?",
    "Sachin Tendulkar",
    "Ricky Ponting",
    "Kumar Sangakkara",
    "Virat Kohli",
    0,
  ],
  [
    "Who holds the record for the most Test centuries as an active player?",
    "Virat Kohli",
    "Steve Smith",
    "Kane Williamson",
    "Joe Root",
    1,
  ],
  [
    "Who holds the record for the fastest century in One Day Internationals?",
    "AB de Villiers",
    "Corey Anderson",
    "Shahid Afridi",
    "Chris Gayle",
    0,
  ],
  [
    "Who is the current captain of the Indian cricket team?",
    "Rohit Sharma",
    "KL Rahul",
    "Shikhar Dhawan",
    "Virat Kohli",
    0,
  ],
  [
    "Which country won the first-ever Cricket World Cup in 1975?",
    "Australia",
    "India",
    "West Indies",
    "England",
    2,
  ],
  [
    "Who has the highest individual score in Test cricket?",
    "Brian Lara",
    "Matthew Hayden",
    "Virender Sehwag",
    "Gary Sobers",
    0,
  ],
  [
    "Which player has taken the most wickets in Test cricket?",
    "James Anderson",
    "Anil Kumble",
    "Shane Warne",
    "Muttiah Muralitharan",
    3,
  ],
  [
    "Which team wore a green jersey for a single match in the Indian Premier League (IPL)?",
    "Mumbai Indians",
    "Chennai Super Kings",
    "Kolkata Knight Riders",
    "Royal Challengers Bangalore",
    3,
  ],

  [
    "Which country won the 2022 FIFA World Cup?",
    "France",
    "Argentina",
    "Brazil",
    "Spain",
    1,
  ],
  [
    "Who is the most decorated Olympian of all time?",
    "Michael Phelps",
    "Usain Bolt",
    "Simone Biles",
    "Serena Williams",
    0,
  ],
  [
    "Which sport is played at Wimbledon?",
    "Golf",
    "Tennis",
    "Cricket",
    "Soccer",
    1,
  ],
  [
    "In which country were the first modern Olympic Games held?",
    "United States",
    "Greece",
    "United Kingdom",
    "France",
    1,
  ],
  [
    "Which city hosted the 2016 Summer Olympics?",
    "Rio de Janeiro",
    "London",
    "Beijing",
    "Tokyo",
    0,
  ],
  [
    "Which city hosted the 2022 Olympics?",
    "Rio de Janeiro",
    "London",
    "Beijing",
    "Tokyo",
    3,
  ],
  [
    "Which sport is associated with the Ryder Cup?",
    "Cricket",
    "Tennis",
    "Golf",
    "Basketball",
    2,
  ],
  [
    "Which athlete is known as 'The Flying Finn'?",
    "Carl Lewis",
    "Jesse Owens",
    "Usain Bolt",
    "Paavo Nurmi",
    3,
  ],
  [
    "Which country has won the most Olympic gold medals?",
    "United States",
    "China",
    "Russia",
    "Germany",
    0,
  ],
  [
    "Which team has won the most Super Bowl titles in the NFL?",
    "New England Patriots",
    "Pittsburgh Steelers",
    "Dallas Cowboys",
    "San Francisco 49ers",
    0,
  ],
  [
    "In which sport can you perform a 'slam dunk'?",
    "Tennis",
    "Basketball",
    "Golf",
    "Soccer",
    1,
  ],
];

let movieQuestions = [
  [
    "Which Indian movie holds the record for the highest-grossing Bollywood film of all time?",
    "Dangal",
    "Baahubali 2: The Conclusion",
    "PK",
    "Bajrangi Bhaijaan",
    1,
  ],
  [
    "Who is known as the 'King of Bollywood'?",
    "Shah Rukh Khan",
    "Amitabh Bachchan",
    "Salman Khan",
    "Rajinikanth",
    0,
  ],
  [
    "Which Indian director is known for the critically acclaimed movie 'Gangs of Wasseypur'?",
    "Anurag Kashyap",
    "Sanjay Leela Bhansali",
    "Imtiaz Ali",
    "Karan Johar",
    0,
  ],
  [
    "Who won the National Film Award for Best Actor for the movie 'Paan Singh Tomar'?",
    "Irrfan Khan",
    "Aamir Khan",
    "Ranbir Kapoor",
    "Shahid Kapoor",
    0,
  ],
  [
    "Which Indian movie won the Best Foreign Language Film at the 89th Academy Awards?",
    "Lagaan",
    "Mother India",
    "Gully Boy",
    "Newton",
    3,
  ],
  [
    "Who is the highest-paid actress in Indian cinema?",
    "Deepika Padukone",
    "Kangana Ranaut",
    "Priyanka Chopra",
    "Kareena Kapoor Khan",
    2,
  ],
  [
    "Which Indian movie won the Palme d'Or at the Cannes Film Festival?",
    "Rang De Basanti",
    "Masaan",
    "Gandhi",
    "Court",
    3,
  ],
  [
    "Who is the director of the Indian movie 'Baahubali: The Beginning'?",
    "Karan Johar",
    "Rajkumar Hirani",
    "S.S. Rajamouli",
    "Sanjay Leela Bhansali",
    2,
  ],
  [
    "Which Indian movie is based on the life of the mathematician Srinivasa Ramanujan?",
    "The Lunchbox",
    "Super 30",
    "Ramanujan",
    "A Beautiful Mind",
    2,
  ],
  [
    "Which Indian movie features the popular song 'Chaiyya Chaiyya'?",
    "Dilwale Dulhania Le Jayenge",
    "Kabhi Khushi Kabhie Gham",
    "Dil Se",
    "Kal Ho Naa Ho",
    2,
  ],
  [
    "Who directed the movie 'Pulp Fiction'?",
    "Steven Spielberg",
    "Quentin Tarantino",
    "Martin Scorsese",
    "Christopher Nolan",
    1,
  ],
  [
    "Which actor portrayed the character of Tony Stark/Iron Man in the Marvel Cinematic Universe?",
    "Robert Downey Jr.",
    "Chris Evans",
    "Chris Hemsworth",
    "Tom Hiddleston",
    0,
  ],
  [
    "Who won the Academy Award for Best Actress for her role in the movie 'La La Land'?",
    "Meryl Streep",
    "Emma Stone",
    "Jennifer Lawrence",
    "Cate Blanchett",
    1,
  ],
  [
    "Which movie features the iconic line 'May the Force be with you'?",
    "Star Wars",
    "The Matrix",
    "The Lord of the Rings",
    "Jurassic Park",
    0,
  ],
  [
    "Who directed the movie 'The Shawshank Redemption'?",
    "Christopher Nolan",
    "Steven Spielberg",
    "Frank Darabont",
    "Martin Scorsese",
    2,
  ],
  [
    "Which actress won an Oscar for her performance in the movie 'Black Swan'?",
    "Natalie Portman",
    "Meryl Streep",
    "Julianne Moore",
    "Cate Blanchett",
    0,
  ],
  [
    "Which movie is based on the novel by Stephen King and features a character named Jack Torrance?",
    "The Shining",
    "Misery",
    "Carrie",
    "The Green Mile",
    0,
  ],
  [
    "Who played the character of Joker in the movie 'The Dark Knight'?",
    "Christian Bale",
    "Tom Hardy",
    "Heath Ledger",
    "Joaquin Phoenix",
    2,
  ],
  [
    "Which movie won the Best Picture award at the 92nd Academy Awards?",
    "1917",
    "Parasite",
    "Once Upon a Time in Hollywood",
    "Joker",
    1,
  ],
  [
    "Who directed the movie 'Inception'?",
    "Christopher Nolan",
    "Martin Scorsese",
    "Quentin Tarantino",
    "Steven Spielberg",
    0,
  ],

  [
    "Who won the Academy Award for Best Actor in 2020?",
    "Joaquin Phoenix",
    "Leonardo DiCaprio",
    "Brad Pitt",
    "Adam Driver",
    0,
  ],
  [
    "Which film won the Best Picture award at the 2020 Oscars?",
    "Parasite",
    "1917",
    "Once Upon a Time in Hollywood",
    "Joker",
    0,
  ],
  [
    "Who directed the movie 'Inception'?",
    "Steven Spielberg",
    "Christopher Nolan",
    "Martin Scorsese",
    "Quentin Tarantino",
    1,
  ],
  [
    "Which film is the highest-grossing of all time?",
    "Avatar",
    "Avengers: Endgame",
    "Titanic",
    "Star Wars: The Force Awakens",
    1,
  ],
  [
    "Who is the director of the 'Harry Potter' film series?",
    "J.K. Rowling",
    "Chris Columbus",
    "David Yates",
    "Alfonso Cuarón",
    2,
  ],
  [
    "Which actress won the Academy Award for Best Actress in 2020?",
    "Scarlett Johansson",
    "Charlize Theron",
    "Renée Zellweger",
    "Saoirse Ronan",
    2,
  ],
  [
    "Which movie features the character Black Panther 1st time?",
    "Captain America: Civil War",
    "Captain America: The First Avenger",
    "Thor",
    "Black Panther",
    0,
  ],
  [
    "Who played the character Jack Sparrow in the 'Pirates of the Caribbean' series?",
    "Tom Hanks",
    "Johnny Depp",
    "Brad Pitt",
    "Will Smith",
    1,
  ],
  [
    "Which film is known for the quote 'Here's Johnny!'?",
    "The Shining",
    "Psycho",
    "A Clockwork Orange",
    "Fight Club",
    0,
  ],
  [
    "Who directed the movie 'The Dark Knight'?",
    "Christopher Nolan",
    "Tim Burton",
    "Zack Snyder",
    "David Fincher",
    0,
  ],
  [
    "Which actress played the character Hermione Granger in the 'Harry Potter' film series?",
    "Emma Watson",
    "Emma Stone",
    "Keira Knightley",
    "Natalie Portman",
    0,
  ],
  [
    "Which movie features the song 'Let It Go'?",
    "Frozen",
    "Moana",
    "Coco",
    "Tangled",
    0,
  ],
  [
    "Who played the character Neo in 'The Matrix' trilogy?",
    "Keanu Reeves",
    "Tom Cruise",
    "Matt Damon",
    "Ryan Gosling",
    0,
  ],
  [
    "Which actor won the Academy Award for Best Supporting Actor in 2020?",
    "Tom Hanks",
    "Brad Pitt",
    "Al Pacino",
    "Joe Pesci",
    1,
  ],
];

let literatureQuestions = [
  [
    "Who wrote the novel 'Pride and Prejudice'?",
    "Jane Austen",
    "Charlotte Brontë",
    "Emily Dickinson",
    "Virginia Woolf",
    0,
  ],
  [
    "In which Shakespeare play does the character Hamlet appear?",
    "Romeo and Juliet",
    "Macbeth",
    "Hamlet",
    "Othello",
    2,
  ],
  [
    "Who is the author of the 'Harry Potter' book series?",
    "J.R.R. Tolkien",
    "J.K. Rowling",
    "George Orwell",
    "C.S. Lewis",
    1,
  ],
  [
    "Which novel features the character Atticus Finch?",
    "To Kill a Mockingbird",
    "The Great Gatsby",
    "1984",
    "Moby-Dick",
    0,
  ],
  [
    "Who wrote the poem 'The Raven'?",
    "Robert Frost",
    "Walt Whitman",
    "Edgar Allan Poe",
    "Emily Dickinson",
    2,
  ],
  [
    "Which author wrote the 'Lord of the Rings' trilogy?",
    "J.R.R. Tolkien",
    "George R.R. Martin",
    "C.S. Lewis",
    "J.K. Rowling",
    0,
  ],
  [
    "In which play by Arthur Miller does the character Willy Loman appear?",
    "Death of a Salesman",
    "The Crucible",
    "All My Sons",
    "A View from the Bridge",
    0,
  ],
  [
    "Who is the author of the novel '1984'?",
    "Aldous Huxley",
    "George Orwell",
    "Ray Bradbury",
    "Kurt Vonnegut",
    1,
  ],
  [
    "Which American writer is known for 'The Catcher in the Rye'?",
    "F. Scott Fitzgerald",
    "J.D. Salinger",
    "Ernest Hemingway",
    "Mark Twain",
    1,
  ],
  [
    "Who wrote the play 'Romeo and Juliet'?",
    "William Shakespeare",
    "Anton Chekhov",
    "Samuel Beckett",
    "Tennessee Williams",
    0,
  ],
  [
    "Which novel is set during the Russian Revolution?",
    "Animal Farm",
    "One Hundred Years of Solitude",
    "War and Peace",
    "Catch-22",
    2,
  ],
  [
    "Who is the author of the novel 'To Kill a Mockingbird'?",
    "Harper Lee",
    "John Steinbeck",
    "Harriet Beecher Stowe",
    "Toni Morrison",
    0,
  ],
  [
    "In which novel does the character Jay Gatsby appear?",
    "The Great Gatsby",
    "The Catcher in the Rye",
    "Brave New World",
    "The Grapes of Wrath",
    0,
  ],
  [
    "Who wrote the play 'Hamlet'?",
    "William Shakespeare",
    "Arthur Miller",
    "Henrik Ibsen",
    "Tom Stoppard",
    0,
  ],
  [
    "Which American poet wrote 'Leaves of Grass'?",
    "Ralph Waldo Emerson",
    "Walt Whitman",
    "Emily Dickinson",
    "Robert Frost",
    1,
  ],
];

let musicQuestions = [
  [
    "Which band released the album 'Abbey Road'?",
    "The Beatles",
    "Led Zeppelin",
    "Queen",
    "The Rolling Stones",
    0,
  ],
  [
    "Who is known as the 'King of Pop'?",
    "Michael Jackson",
    "Elvis Presley",
    "Stevie Wonder",
    "Prince",
    0,
  ],
  [
    "Which artist recorded the song 'Bohemian Rhapsody'?",
    "Queen",
    "The Rolling Stones",
    "Elton John",
    "David Bowie",
    0,
  ],
  [
    "Which instrument does Yo-Yo Ma play?",
    "Piano",
    "Violin",
    "Cello",
    "Trumpet",
    2,
  ],
  [
    "Which singer-songwriter wrote the song 'Like a Rolling Stone'?",
    "Bob Dylan",
    "Johnny Cash",
    "Bruce Springsteen",
    "Jimi Hendrix",
    0,
  ],
  [
    "Which rock band performed the song 'Stairway to Heaven'?",
    "Led Zeppelin",
    "The Who",
    "Pink Floyd",
    "AC/DC",
    0,
  ],
  [
    "Who is the lead vocalist of the band U2?",
    "Bono",
    "Chris Martin",
    "Thom Yorke",
    "Eddie Vedder",
    0,
  ],
  [
    "Which artist released the album 'Thriller'?",
    "Prince",
    "Elton John",
    "David Bowie",
    "Michael Jackson",
    3,
  ],
  [
    "Who composed the symphony 'Symphony No. 9 in D minor'?",
    "Ludwig van Beethoven",
    "Wolfgang Amadeus Mozart",
    "Johann Sebastian Bach",
    "Franz Schubert",
    0,
  ],
  [
    "Which country is flamenco music associated with?",
    "Spain",
    "Italy",
    "France",
    "Argentina",
    0,
  ],
  [
    "Who is the lead guitarist of the band Guns N' Roses?",
    "Slash",
    "Jimmy Page",
    "Eric Clapton",
    "Eddie Van Halen",
    0,
  ],
  [
    "Which artist recorded the album 'Purple Rain'?",
    "Prince",
    "Michael Jackson",
    "David Bowie",
    "Elvis Presley",
    0,
  ],
  [
    "Who composed the ballet 'Swan Lake'?",
    "Pyotr Ilyich Tchaikovsky",
    "Igor Stravinsky",
    "Claude Debussy",
    "Sergei Prokofiev",
    0,
  ],
  [
    "Which artist released the song 'Imagine'?",
    "Bob Dylan",
    "John Lennon",
    "Paul McCartney",
    "George Harrison",
    1,
  ],
  [
    "Which genre of music originated in Jamaica?",
    "Reggae",
    "Salsa",
    "Hip Hop",
    "Country",
    0,
  ],
  [
    "Who is known as the 'Mozart of Madras' in the Indian music industry?",
    "Arijit Singh",
    "AR Rahman",
    "Shankar Mahadevan",
    "Sonu Nigam",
    1,
  ],
  [
    "Which Indian playback singer has the most number of National Film Awards?",
    "Lata Mangeshkar",
    "Kishore Kumar",
    "Asha Bhosle",
    "Shreya Ghoshal",
    0,
  ],
  [
    "Which music director duo is popularly known as 'Vishal-Shekhar'?",
    "Vishal Dadlani and Shekhar Ravjiani",
    "Vishal Bhardwaj and Shekhar Kapur",
    "Vishal Mishra and Shekhar Malhotra",
    "Vishal Anand and Shekhar Chand",
    0,
  ],
  [
    "Who is the first Indian musician to have a wax statue at Madame Tussauds?",
    "A.R. Rahman",
    "Lata Mangeshkar",
    "Kishore Kumar",
    "Sonu Nigam",
    0,
  ],
  [
    "Which Indian singer is known for her distinctive voice and singing style called 'Sufi-Kathak'?",
    "Sunidhi Chauhan",
    "Shalmali Kholgade",
    "Rekha Bhardwaj",
    "Richa Sharma",
    2,
  ],
  [
    "Which Indian playback singer is also known as the 'Nightangle of India'?",
    "Shreya Ghoshal",
    "Sunidhi Chauhan",
    "Neha Kakkar",
    "Alka Yagnik",
    0,
  ],
  [
    "Who is the composer of the popular song 'Kolaveri Di'?",
    "Vishal Dadlani",
    "Pritam Chakraborty",
    "Himesh Reshammiya",
    "Anirudh Ravichander",
    3,
  ],
  [
    "Which Indian playback singer is known for his soulful renditions in movies like 'Tum Hi Ho' and 'Janam Janam'?",
    "Arijit Singh",
    "Atif Aslam",
    "Mohit Chauhan",
    "Rahat Fateh Ali Khan",
    0,
  ],
  [
    "Which Indian musician composed the soundtrack for the movie 'Slumdog Millionaire'?",
    "Shankar Mahadevan",
    "A.R. Rahman",
    "Vishal-Shekhar",
    "Mithoon",
    1,
  ],
  [
    "Who is known as the 'Bhangra King' in the Indian music industry?",
    "Badshah",
    "Honey Singh",
    "Guru Randhawa",
    "Daler Mehndi",
    3,
  ],
  [
    "Which Indian playback singer is also known for his acting in movies like 'Rock On!!' and 'Zindagi Na Milegi Dobara'?",
    "Sonu Nigam",
    "Mohit Chauhan",
    "Farhan Akhtar",
    "Arijit Singh",
    2,
  ],
  [
    "Which Indian playback singer has the nickname 'King of Romance'?",
    "Udit Narayan",
    "Kumar Sanu",
    "Sonu Nigam",
    "Hariharan",
    1,
  ],
  [
    "Who composed the soundtrack for the Indian movie 'Dilwale Dulhania Le Jayenge'?",
    "Anu Malik",
    "Jatin-Lalit",
    "Shankar-Ehsaan-Loy",
    "Vishal-Shekhar",
    1,
  ],
  [
    "Which Indian playback singer is known for his energetic performances and hit songs like 'Baby Doll' and 'Chittiyan Kalaiyaan'?",
    "Mika Singh",
    "Arijit Singh",
    "Yo Yo Honey Singh",
    "Badshah",
    0,
  ],
  [
    "Who is the first Indian musician to perform at the prestigious Wembley Stadium in London?",
    "Asha Bhosle",
    "Sonu Nigam",
    "A.R. Rahman",
    "Shreya Ghoshal",
    2,
  ],
];
